name: API E2E Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build and Run E2E tests
      uses: isbang/compose-action@v1.4.1
      with:
        up-flags: pnpm test
        compose-file: "./docker-compose.yml"
        services: |
          e2e
