name: API E2E Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: 7.26.3

    - name: Install dependencies
      run: pnpm install

    - name: Run E2E tests
      run: pnpm test

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
